# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: papers/
    weight: 11
  - name: Activities
    url: activities/
    weight: 12
  - name: Teaching
    url: teaching/
    weight: 13
  - name: Open Positions
    url: open-positions/
    weight: 14
  - name: Contact
    url: contact/
    weight: 15
